# This line specifies the official Playwright Docker image
steps:

- name: 'mcr.microsoft.com/playwright:v1.43.1-jammy'
  args: ['yarn', '--frozen-lockfile']

- name: 'mcr.microsoft.com/playwright:v1.43.1-jammy'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      yarn playwright install chrome \
      && yarn test
  env:
  - 'CI=true'
  allowFailure: true

- name: "gcr.io/cloud-builders/gcloud-slim"
  args: [
    "storage",
    "cp",
    "--recursive",
    "playwright-report",
    "gs://vierageorge-pw-poc/$BUILD_ID/",
  ]

# Parse the output to extract the public URL
- name: 'bash'
  args:
  - '-c'  # Execute a shell command
  - echo "https://storage.googleapis.com/vierageorge-pw-poc/$BUILD_ID/playwright-report/index.html"